[workspace]
resolver = "2"
members = ["crates/*", "lib/*"]

[workspace.package]
authors = ["Patrick van der Velde"]
repository = "https://github.com/pvandervelde/glitch_guardian"
version = "0.1.0"
license-file = "LICENSE"

[workspace.dependencies]
anyhow = "1.0.86"
