name: Deploy to Azure Functions

on:
  workflow_dispatch:
#  push:
#    # Only run the deploy when we do a tag push
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
#      - '!*-rc[0-9]+'
  release:
    types:
      - published

# Sets permissions of the GITHUB_TOKEN to allow deployment to Azure
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@a94a3b62ee018ef5346cb08fd0d63d93811fe691 # v3.0.0
      with:
        versionSpec: '6.0.0'

    - name: Determine Version
      id: version_step # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@a94a3b62ee018ef5346cb08fd0d63d93811fe691 # v3.0.0
      with:
        useConfigFile: true

    - name: Set up Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
      with:
        toolchain: stable

    - name: Install cargo binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install cross
      run: cargo binstall cross --no-confirm --no-track

    - name: Build handler
      run: cross build --release --package handler --target x86_64-unknown-linux-musl

    - name: show output directories
      run: |
        ls -la
        ls -la target
        ls -la target/release

    - name: Build xtask
      run: cargo build --release --package xtask

    - name: XTask
      run: cargo xtask

    - name: show directories
      run: |
        ls -la
        ls -la target
        ls -la target/func

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

    - name: Azure Login
      uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform init
      working-directory: env
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform Apply
      working-directory: env
      run: |
        terraform apply -auto-approve \
          -var="github_app_id=${{ secrets.GH_APP_ID }}" \
          -var="github_app_private_key=${{ secrets.GH_APP_PRIVATE_KEY }}" \
          -var="github_project_id=${{ secrets.GH_PROJECT_ID }}" \
          -var="github_webhook_secret=${{ secrets.GH_WEBHOOK_SECRET }}" \
          -var="meta_git_sha=${{ github.sha }}" \
          -var="meta_version=${{ env.majorMinorPatch }}"
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true

    # Don't use the publish profile for custom handlers
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@fd80521afbba9a2a76a99ba1acc07aff8d733d11 # v1
      with:
        app-name: p-aue-tf-glitchg-function
        package: ${{ github.workspace }}/target/func
